#!/bin/sh
echo "------------------------------------------------------------"
echo "Decrypting files"
yadm decrypt # (enter password)
echo "Starting ssh-agent and adding SSH key"
eval $(ssh-agent -s)
ssh-add ~/.ssh/github_id_rsa
echo "Testing ssh connection to github.com"
ssh -T git@github.com
echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:iancleary/dotfiles.git"

# https://github.com/TheLocehiliosan/yadm/issues/232
# still clones into master branch, remove when ^ is resolved
yadm checkout -b main
yadm branch -D master

echo "------------------------------------------------------------"
